In [1]:
import numpy as np
import pandas as pd

In [2]:
x = np.array([
    [1,2,3,4,5],
    [10,20,30,40,50]
])
y = np.array([0,1])

In [3]:
for a,b in zip(x,y):
    print(a,b)

[1 2 3 4 5] 0
[10 20 30 40 50] 1


In [5]:
rgen = np.random.RandomState(1)
w = rgen.normal(loc=0.0, scale=0.01, size=1+5)

In [6]:
w

array([ 0.01624345, -0.00611756, -0.00528172, -0.01072969,  0.00865408,
       -0.02301539])

# 퍼셉트론 API

In [7]:
class Perceptron(object):
    def __init__(self, eta=0.01, n_iter=50, random_state=1):
        self.eta = eta
        self.n_iter = n_iter
        self.random_state = random_state
    # 학습함수
    def fit(self, X,y):
        # 가중치 초기화를 위한 시드값 고정
        rgen=np.random.RandomState(self.random_state)
        # 가중치 초기화 생성
        self.w_ = rgen.normal(loc=0.0, scale=0.01, size=1+X.shape[1])
        self.errors_ = []
        for _ in range(self.n_iter):
            errors = 0
            for xi, target in zip(X,y):
                update = self.eta*(target-self.predict(xi))
                self.w_[1:] += update*xi
                self.w_[0] += update
                errors += int(update != 0.0)
            self.errors_.append(errors)
        return self
    def net_input(self, X):
        return np.dot(X, self.w_[1:]) + self.w_[0]

In [8]:
p = Perceptron()

In [9]:
p.eta

0.01