In [21]:
f = open('./test.txt', 'r')

In [22]:
contents = f.read()

In [6]:
contents

'The House has adjourned for the third day without electing a new speaker after Kevin McCarthy continued to suffer a string of defeats in multiple rounds of voting on Thursday. As the fight for the gavel drags on, it has now become the longest speaker contest in 164 years.\nEach failed vote only increases pressure on McCarthy to end the impasse, but it is unclear whether he will be able to pull it off as the situation grows increasingly dire for his future political prospects.'

In [7]:
f.close()

In [23]:
with open('test.txt', 'r') as f:
    content = f.readlines()
    print(content)

['The House has adjourned for the third day without electing a new speaker after Kevin McCarthy continued to suffer a string of defeats in multiple rounds of voting on Thursday. As the fight for the gavel drags on, it has now become the longest speaker contest in 164 years.\n', 'Each failed vote only increases pressure on McCarthy to end the impasse, but it is unclear whether he will be able to pull it off as the situation grows increasingly dire for his future political prospects.']


In [25]:
# 라인단위로 읽는 경우
with open('./test.txt', 'r') as f:
    #f.readline()으로 읽어서 값이 없을때까지 f.readline()
    while True:
        content = f.readline()
        if not content: break
        content = content.replace('\n', '')
        print(content)

The House has adjourned for the third day without electing a new speaker after Kevin McCarthy continued to suffer a string of defeats in multiple rounds of voting on Thursday. As the fight for the gavel drags on, it has now become the longest speaker contest in 164 years.
Each failed vote only increases pressure on McCarthy to end the impasse, but it is unclear whether he will be able to pull it off as the situation grows increasingly dire for his future political prospects.


### 알파벳수 count
### 공백을 기준으로 분리한 문자들의 count
### 라인수 count

In [36]:
with open('./test.txt', 'r') as f:
    content_list = f.readlines()
    lines_count = len(content_list)
    word_count = sum([len(line.split()) for line in content_list])
    word_list = [line.split() for line in content_list]
    spell_count = sum([len(j) for j in [i.replace('\n','') for i in content_list]])
    print(f"라인 수: {lines_count}, 단어 수: {word_count}, 글자 수: {spell_count}")

라인 수: 2, 단어 수: 85, 글자 수: 478


In [30]:
word_list

[['The',
  'House',
  'has',
  'adjourned',
  'for',
  'the',
  'third',
  'day',
  'without',
  'electing',
  'a',
  'new',
  'speaker',
  'after',
  'Kevin',
  'McCarthy',
  'continued',
  'to',
  'suffer',
  'a',
  'string',
  'of',
  'defeats',
  'in',
  'multiple',
  'rounds',
  'of',
  'voting',
  'on',
  'Thursday.',
  'As',
  'the',
  'fight',
  'for',
  'the',
  'gavel',
  'drags',
  'on,',
  'it',
  'has',
  'now',
  'become',
  'the',
  'longest',
  'speaker',
  'contest',
  'in',
  '164',
  'years.'],
 ['Each',
  'failed',
  'vote',
  'only',
  'increases',
  'pressure',
  'on',
  'McCarthy',
  'to',
  'end',
  'the',
  'impasse,',
  'but',
  'it',
  'is',
  'unclear',
  'whether',
  'he',
  'will',
  'be',
  'able',
  'to',
  'pull',
  'it',
  'off',
  'as',
  'the',
  'situation',
  'grows',
  'increasingly',
  'dire',
  'for',
  'his',
  'future',
  'political',
  'prospects.']]

In [32]:
[i.replace('\n', '') for i in content_list]

['The House has adjourned for the third day without electing a new speaker after Kevin McCarthy continued to suffer a string of defeats in multiple rounds of voting on Thursday. As the fight for the gavel drags on, it has now become the longest speaker contest in 164 years.',
 'Each failed vote only increases pressure on McCarthy to end the impasse, but it is unclear whether he will be able to pull it off as the situation grows increasingly dire for his future political prospects.']

In [37]:
temp_list = ['the', 'abc', 'a', 'the', 'b', 'c']

In [38]:
word_count = {}
word_count['the'] = 1

In [39]:
word_count['the'] += 1

In [40]:
word_count

{'the': 2}

In [41]:
word_count = {}
for word in temp_list:
    if word not in word_count.keys():
        word_count[word] = 1
    else:
        word_count[word] += 1
word_count

{'the': 2, 'abc': 1, 'a': 1, 'b': 1, 'c': 1}

In [50]:
with open('./hangeul.txt', 'r', encoding = 'utf-8') as f:
    temp = f.read().split()
    result = makeWordCount(temp)

In [49]:
def makeWordCount(temp_list):
    word_count = {}
    for word in temp_list:
        if word not in word_count.keys():
            word_count[word] = 1
        else:
            word_count[word] += 1
    return word_count

In [47]:
a = [i.split() for i in content_list]
temp = []
for i in a:
    temp += i
temp

['본',
 '수업을',
 '통하여',
 '머신러닝의',
 '기초',
 '알고리즘을',
 '이해하고',
 '구현해봄으로써',
 '기초를',
 '습득하고,',
 '더',
 '나아가',
 '이번',
 '실습에',
 '사용되지',
 '않은',
 '다른',
 '머신러닝',
 '알고리즘도',
 '스스로',
 '이해할',
 '수',
 '있는',
 '개발자로',
 '성장할',
 '수',
 '있는',
 '계기를',
 '만드는',
 '데',
 '있습니다.']

# 넘파이

In [53]:
pip install numpy

     --------------------------------------- 14.8/14.8 MB 12.6 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.


In [54]:
import numpy as np

In [55]:
data_1 = [1,2,3,4,5]
data_1

[1, 2, 3, 4, 5]

In [57]:
data_2 = [
    [1,2,3],
    [4,5,6]
]
data_2

[[1, 2, 3], [4, 5, 6]]

In [59]:
data_3 = [
    [
        [1,2,3],
        [4,5,6]
    ],
    [
        [7,8,9],
        [10,11,12]
    ]
]
data_3

[[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]]

In [58]:
vector_1 = np.array(data_1)
vector_1

array([1, 2, 3, 4, 5])

In [60]:
matrix_1 = np.array(data_2)
matrix_2 = np.array(data_3)

In [61]:
matrix_1, matrix_2

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[[ 1,  2,  3],
         [ 4,  5,  6]],
 
        [[ 7,  8,  9],
         [10, 11, 12]]]))

In [62]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [63]:
np.ones((2,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [64]:
np.empty(10)

array([1.17041373e-311, 1.77863633e-322, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 2.03891917e+160, 5.92935067e-038, 6.81855440e-091,
       2.36003737e+180, 4.16142136e-315])

In [65]:
np.empty((2,2))

array([[2.12199579e-314, 1.16921968e-311],
       [6.77858066e-321, 1.16921968e-311]])

In [66]:
np.array(5)

array(5)

In [67]:
np.full(5,3)

array([3, 3, 3, 3, 3])

In [68]:
np.full((2,2),10)

array([[10, 10],
       [10, 10]])

In [69]:
type(vector_1)

numpy.ndarray

In [72]:
# dtype: 자료형 안에 들어있는 데이터의 타입
vector_1.dtype

dtype('int32')

In [73]:
# 자료형의 차수
vector_1.ndim

1

In [74]:
matrix_1.ndim, matrix_2.ndim

(2, 3)

In [75]:
vector_1.shape

(5,)

In [77]:
# 행렬의 크기를 알려준다
# 1차원이면 갯수
matrix_1.shape

(2, 3)

In [78]:
matrix_2.shape

(2, 2, 3)

In [79]:
vector_1.size

5

In [80]:
matrix_1.size

6

### dtype
### 다차원 배열을 생성할 때 데이터 값을 지정할 수 있다

In [82]:
vec_dtype = np.array([1,2,3,4,5], dtype = np.int64)
matrix_dtype = np.array(
    [
        [1,2,3],
        [4,5,6]
    ],
    dtype = np.float64
)

In [83]:
# 데이터 타입, 차수, 셰이프
vec_dtype.dtype, vec_dtype.ndim, vec_dtype.shape

(dtype('int64'), 1, (5,))

In [84]:
matrix_dtype.dtype, matrix_dtype.ndim, matrix_dtype.shape

(dtype('float64'), 2, (2, 3))

### astype
### 자료형을 변경

In [86]:
arr_float1 = np.array([1.5, 1.3, 1.2], dtype = np.float64)
arr_float1.dtype

dtype('float64')

In [87]:
arr_int = arr_float1.astype(np.int64)
arr_int.dtype, arr_int

(dtype('int64'), array([1, 1, 1], dtype=int64))

### 문자열 to 부동소수점

In [88]:
arr_str = np.array(['-2.5','12.2','1.9'], dtype=np.string_)
arr_str.dtype, arr_str

(dtype('S4'), array([b'-2.5', b'12.2', b'1.9'], dtype='|S4'))

In [89]:
arr_float = arr_str.astype(np.float64)
arr_float.dtype, arr_float

(dtype('float64'), array([-2.5, 12.2,  1.9]))

In [ ]:
vector_1 = np.array([1,2,3,4,5])
matrix_2 = np.array(
    [
        [1,2,3,4,5],
        [6,7,8,9,10],
        [11,12,13,14,15]
    ]
)

In [91]:
matrix_2.shape

(3, 5)

# 인덱싱

### vector_1에서 값 3을 출력
### vector_1에서 마지막 값 출력
### matrix_2에서 9를 출력
### matrix_2에서 마지막 row의 마지막 값을 출력

In [96]:
vector_1[2], vector_1[-1], matrix_2[1][3], matrix_2[-1][-1]

(3, 5, 9, 15)

In [97]:
vector_1 = np.array([1,2,3,4,5], dtype = np.int32)
print(vector_1[:])
print(vector_1[:4])
print(vector_1[1:3])
print(vector_1[2:])
print(vector_1[2:-1])

[1 2 3 4 5]
[1 2 3 4]
[2 3]
[3 4 5]
[3 4]


In [99]:
matrix_2 = np.array([
    [
        [0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14],[15,16,17,18,19],[20,21,22,23,24]
    ]
]
    ,np.int32
)

In [100]:
matrix_2

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]]])

In [101]:
print(matrix_2[:2, 3:])
print(matrix_2[4], matrix_2[4,3], matrix_2[4,4])

[[[15 16 17 18 19]
  [20 21 22 23 24]]]


IndexError: index 4 is out of bounds for axis 0 with size 1