In [1]:
import numpy as np

In [2]:
matrix = np.array(
    [
    [1,2,3],
    [4,5,6],
    [7,8,9]
    ]
)

In [3]:
matrix.shape

(3, 3)

In [5]:
print(f"합: {np.sum(matrix)}")
print(f"합: {matrix.sum()}")

print(f"평균: {np.mean(matrix)}")
print(f"평균: {matrix.mean()}")

print(f"표준편차: {np.std(matrix)}")
print(f"표준편차: {matrix.std()}")

print(f"분산: {np.var(matrix)}")
print(f"분산: {matrix.var()}")

합: 45
합: 45
평균: 5.0
평균: 5.0
표준편차: 2.581988897471611
표준편차: 2.581988897471611
분산: 6.666666666666667
분산: 6.666666666666667


In [9]:
print(f"전체 데이터의 최대값: {np.max(matrix)}")
print(f"열에서 최대값: {np.max(matrix, axis=0)}")
print(f"열에서 최소값: {np.min(matrix, axis=0)}")
print(f"열에서 평균값: {np.mean(matrix, axis=0)}")
print(f"행에서 최대값: {np.max(matrix, axis=1)}")
print(f"행에서 최소값: {np.min(matrix, axis=1)}")
print(f"행에서 평균값: {np.mean(matrix, axis=1)}")

전체 데이터의 최대값: 9
열에서 최대값: [7 8 9]
열에서 최소값: [1 2 3]
열에서 평균값: [4. 5. 6.]
행에서 최대값: [3 6 9]
행에서 최소값: [1 4 7]
행에서 평균값: [2. 5. 8.]


# 난수생성

    seed: 씨앗
    rand: 균등 분포한 난수를 생성
    random: 실수형 난수를 생성
    randint: 지정한 최소 최대 범위안에서 난수 생성
    randn: 정규분포
    uniform: 임의의 분포에서 표본추출
    random_sample: 0.0 ~ 1.0 사이에서 실수
    standard_normal: 정규분포
    choice: 랜덤하게 샘플을 선택
    shuffle: 순서를 뒤섞는다

In [10]:
# 난수를 생성(seed 값 고정)
np.random.seed(0)

In [15]:
import numpy.random as rd

In [20]:
print(f"0과 1사이의 실수 난수: {rd.random(10)}")
print(f"0과 45사이의 6개 정수를 생성: {rd.randint(0,46,6)}")
print(f"평균이 0.0이고 표준편차가 1.0인 정규분포에서 5개: {rd.normal(0.0,1.0,5)}")
print(f"{rd.standard_normal(3)}")

0과 1사이의 실수 난수: [0.16494046 0.36980809 0.14644176 0.56961841 0.70373728 0.28847644
 0.43328806 0.75610669 0.39609828 0.89603839]
0과 45사이의 6개 정수를 생성: [ 3 44 14 32  4  3]
평균이 0.0이고 표준편차가 1.0인 정규분포에서 5개: [-2.15367459 -1.07075262  1.05445173 -0.40317695  1.22244507]
[0.20827498 0.97663904 0.3563664 ]


In [21]:
vector = [1,2,3,4,5,6,7,8,9]
rd.choice(vector,3)

array([7, 6, 4])

In [22]:
rd.shuffle(vector)

In [23]:
vector

[3, 7, 9, 6, 4, 5, 8, 1, 2]

# sort

In [24]:
# 평균이 0이고 표준편차가 1인 정규분포 형태의 데이터 5개
vector = np.random.randn(5)
vector

array([ 0.70657317,  1.03081595, -1.27698899,  0.83771977, -1.49011141])

In [25]:
print(f"1차원 배열 sort() 정렬 전: {vector}")
vector.sort()
print(f"1차원 배열 sort() 정렬 후: {vector}")

1차원 배열 sort() 정렬 전: [ 0.70657317  1.03081595 -1.27698899  0.83771977 -1.49011141]
1차원 배열 sort() 정렬 후: [-1.49011141 -1.27698899  0.70657317  0.83771977  1.03081595]


In [29]:
# 2차원 데이터 정렬
matrix_1 = np.random.random((3,3))*10
matrix_1

array([[2.30742335, 7.64911699, 9.44123519],
       [7.49999249, 3.39403819, 4.89548937],
       [3.38985117, 1.79490261, 1.70986599]])

In [30]:
print(f"2차원 배열 sort() 정렬 전: {matrix_1}")
matrix_1.sort()
print(f"2차원 배열 sort() 정렬 후: {matrix_1}")

2차원 배열 sort() 정렬 전: [[2.30742335 7.64911699 9.44123519]
 [7.49999249 3.39403819 4.89548937]
 [3.38985117 1.79490261 1.70986599]]
2차원 배열 sort() 정렬 후: [[2.30742335 7.64911699 9.44123519]
 [3.39403819 4.89548937 7.49999249]
 [1.70986599 1.79490261 3.38985117]]


In [31]:
import copy

In [32]:
matrix_1 = np.random.random((3,3))*10
matrix_2 = copy.deepcopy(matrix_1)

In [33]:
matrix_1, matrix_2

(array([[4.63450977, 8.74572958, 9.44119751],
        [6.08252866, 5.96655406, 7.83644245],
        [5.00026298, 0.50370057, 6.99098075]]),
 array([[4.63450977, 8.74572958, 9.44119751],
        [6.08252866, 5.96655406, 7.83644245],
        [5.00026298, 0.50370057, 6.99098075]]))

In [34]:
matrix_1.sort()
matrix_1

array([[4.63450977, 8.74572958, 9.44119751],
       [5.96655406, 6.08252866, 7.83644245],
       [0.50370057, 5.00026298, 6.99098075]])

In [35]:
matrix_2.sort(axis=1)
matrix_2

array([[4.63450977, 8.74572958, 9.44119751],
       [5.96655406, 6.08252866, 7.83644245],
       [0.50370057, 5.00026298, 6.99098075]])

In [36]:
matrix_2.sort(axis=0)
matrix_2

array([[0.50370057, 5.00026298, 6.99098075],
       [4.63450977, 6.08252866, 7.83644245],
       [5.96655406, 8.74572958, 9.44119751]])

In [37]:
# 첫 번째 행만 정렬
print(f"2차원 배열의 첫 번째 행만 정렬 전: {matrix_1}")
matrix_1.sort()
print(f"2차원 배열의 첫 번째 행만 정렬 후: {matrix_1}")

2차원 배열의 첫 번째 행만 정렬 전: [[4.63450977 8.74572958 9.44119751]
 [5.96655406 6.08252866 7.83644245]
 [0.50370057 5.00026298 6.99098075]]
2차원 배열의 첫 번째 행만 정렬 후: [[4.63450977 8.74572958 9.44119751]
 [5.96655406 6.08252866 7.83644245]
 [0.50370057 5.00026298 6.99098075]]


In [38]:
# 슬라이스를 이용해서 첫 번째 행만 가져오기
matrix_1[0,:]

array([4.63450977, 8.74572958, 9.44119751])

In [40]:
# argsort: key를 기준으로 데이터를 정렬
matrix_1 = np.random.rand(5,5)
print("랜덤으로 생성된 2차원 배열", matrix_1)

랜덤으로 생성된 2차원 배열 [[6.07045061e-01 7.14696936e-01 4.69497183e-01 4.56014623e-01
  9.06418087e-01]
 [1.37220420e-01 2.29219323e-01 8.81585399e-01 9.04424976e-01
  6.45784599e-01]
 [3.24682972e-01 5.19711194e-01 5.53568650e-05 3.11860221e-01
  4.25451538e-01]
 [8.85337660e-01 6.79879456e-01 4.56129772e-01 4.83408617e-01
  7.88739428e-01]
 [2.29441834e-01 8.80297603e-01 3.13692393e-01 9.57450856e-01
  4.71751571e-01]]


In [41]:
# key가 되는 1차원 배열 생성
vector = np.array([5,3,1,2,4])

In [44]:
matrix_1[0] = vector
print("matrix 배열의 첫 번째 열에 vector 배열의 요소값을 대입: ", matrix_1)

matrix 배열의 첫 번째 열에 vector 배열의 요소값을 대입:  [[5.00000000e+00 3.00000000e+00 1.00000000e+00 2.00000000e+00
  4.00000000e+00]
 [1.37220420e-01 2.29219323e-01 8.81585399e-01 9.04424976e-01
  6.45784599e-01]
 [3.24682972e-01 5.19711194e-01 5.53568650e-05 3.11860221e-01
  4.25451538e-01]
 [8.85337660e-01 6.79879456e-01 4.56129772e-01 4.83408617e-01
  7.88739428e-01]
 [2.29441834e-01 8.80297603e-01 3.13692393e-01 9.57450856e-01
  4.71751571e-01]]


In [48]:
# 주어진 하나 이상의 숫자(key)를 기준으로 데이터를 정렬할 때 argsort() 사용
print(f"argsort()로 정렬된 배열: {matrix_1[ :, matrix_1[0].argsort()]}")

argsort()로 정렬된 배열: [[1.00000000e+00 2.00000000e+00 3.00000000e+00 4.00000000e+00
  5.00000000e+00]
 [8.81585399e-01 9.04424976e-01 2.29219323e-01 6.45784599e-01
  1.37220420e-01]
 [5.53568650e-05 3.11860221e-01 5.19711194e-01 4.25451538e-01
  3.24682972e-01]
 [4.56129772e-01 4.83408617e-01 6.79879456e-01 7.88739428e-01
  8.85337660e-01]
 [3.13692393e-01 9.57450856e-01 8.80297603e-01 4.71751571e-01
  2.29441834e-01]]


In [49]:
matrix_1[ :,[2,3,1,4,0]]

array([[1.00000000e+00, 2.00000000e+00, 3.00000000e+00, 4.00000000e+00,
        5.00000000e+00],
       [8.81585399e-01, 9.04424976e-01, 2.29219323e-01, 6.45784599e-01,
        1.37220420e-01],
       [5.53568650e-05, 3.11860221e-01, 5.19711194e-01, 4.25451538e-01,
        3.24682972e-01],
       [4.56129772e-01, 4.83408617e-01, 6.79879456e-01, 7.88739428e-01,
        8.85337660e-01],
       [3.13692393e-01, 9.57450856e-01, 8.80297603e-01, 4.71751571e-01,
        2.29441834e-01]])

In [59]:
matrix_2[ :,2:3]

array([[6.99098075],
       [7.83644245],
       [9.44119751]])

In [51]:
# 행렬 즉 매트릭스를 만들고 from ~ to 형태로 데이터 가져오는거 연습
temp = np.random.randn(3,3)
temp

array([[-0.77963481,  0.47633669,  0.83388012],
       [ 1.31379269, -0.6017086 , -0.5471638 ],
       [ 0.60965079,  0.75893216, -1.18591918]])

In [52]:
temp[0,0]

-0.7796348081534819

In [56]:
temp[0,(0,1,2)], temp[0, 0:3], temp[0, :3]

(array([-0.77963481,  0.47633669,  0.83388012]),
 array([-0.77963481,  0.47633669,  0.83388012]),
 array([-0.77963481,  0.47633669,  0.83388012]))

In [57]:
temp[(0,1,2), 0], temp[0:3, 0], temp[:3, 0], temp[:, 0]

(array([-0.77963481,  1.31379269,  0.60965079]),
 array([-0.77963481,  1.31379269,  0.60965079]),
 array([-0.77963481,  1.31379269,  0.60965079]),
 array([-0.77963481,  1.31379269,  0.60965079]))

# 배열의 크기 바꾸기

In [60]:
# 배열의 크기가 (5,4) 행렬 즉 matrix 데이터는 1 ~ 20까지
data = [
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12],
    [13,14,15,16],
    [17,18,19,20]
]

In [61]:
data = np.zeros((5,4))
count = 1
for i in range(5):
    for j in range(4):
        data[i,j] = count
        count += 1
data

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.],
       [13., 14., 15., 16.],
       [17., 18., 19., 20.]])

In [62]:
# (4,5) (2,10)
data.reshape(2,10)

array([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
       [11., 12., 13., 14., 15., 16., 17., 18., 19., 20.]])

In [63]:
data.reshape(5,4)

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.],
       [13., 14., 15., 16.],
       [17., 18., 19., 20.]])

In [65]:
# 주의사항: 배열의 크기를 변경할 때는 행과 열의 수가 같아야 한다
# 따라서 함수 또는 shape를 사용해서 크기를 먼저 알아야 한다
print(f"matrix size: {data.size}")
print(f"matrix shape: {data.shape}")

matrix size: 20
matrix shape: (5, 4)


In [68]:
print(f"reshape(1, -1): {data.reshape(1,-1)}")
print(f"reshape(1, 20): {data.reshape(1,20)}")
print(f"reshape(-1, 20): {data.reshape(-1,20)}")

reshape(1, -1): [[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
  19. 20.]]
reshape(1, 20): [[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
  19. 20.]]
reshape(-1, 20): [[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
  19. 20.]]


In [69]:
# row 2
data.reshape(-1, 5)

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.],
       [11., 12., 13., 14., 15.],
       [16., 17., 18., 19., 20.]])

# 전치

In [70]:
data.T

array([[ 1.,  5.,  9., 13., 17.],
       [ 2.,  6., 10., 14., 18.],
       [ 3.,  7., 11., 15., 19.],
       [ 4.,  8., 12., 16., 20.]])

In [71]:
data.transpose()

array([[ 1.,  5.,  9., 13., 17.],
       [ 2.,  6., 10., 14., 18.],
       [ 3.,  7., 11., 15., 19.],
       [ 4.,  8., 12., 16., 20.]])

In [73]:
data.swapaxes(0,1)

array([[ 1.,  5.,  9., 13., 17.],
       [ 2.,  6., 10., 14., 18.],
       [ 3.,  7., 11., 15., 19.],
       [ 4.,  8., 12., 16., 20.]])

In [74]:
data

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.],
       [13., 14., 15., 16.],
       [17., 18., 19., 20.]])

In [75]:
data.reshape(1,-1)

array([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
        14., 15., 16., 17., 18., 19., 20.]])

In [76]:
list(data.reshape(1,-1)[0])

[1.0,
 2.0,
 3.0,
 4.0,
 5.0,
 6.0,
 7.0,
 8.0,
 9.0,
 10.0,
 11.0,
 12.0,
 13.0,
 14.0,
 15.0,
 16.0,
 17.0,
 18.0,
 19.0,
 20.0]

In [77]:
data.flatten()

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20.])

In [79]:
# flatten() 함수는 데이터를 1차원 데이터로 손쉽게 만들어 준다
np.zeros((1,2,3)).flatten()

array([0., 0., 0., 0., 0., 0.])

In [81]:
from random import sample

In [82]:
sample([1,2,3,4,5,6,7],3)

[2, 4, 1]

In [83]:
np.random.choice([1,2,3,4,5,6,7],3)

array([7, 2, 4])

# numpy 산술 연산과 선형대수

In [87]:
# 2차원 배열 2개 각각 (3,3) (3,3)
# 0 ~ 10 사이에 임의로
m1 = np.array([
    [1,2,3],[4,5,6],[7,8,9]
])
m2 = np.array(sample(range(20),9))
m2 = m2.reshape(3,3)

m1.shape, m2.shape

((3, 3), (3, 3))

In [88]:
m1, m2

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[17, 14, 13],
        [ 4,  2, 10],
        [ 8, 11,  5]]))

In [89]:
m1, m1+2

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]]))

In [90]:
m1, m2, m1+m2

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[17, 14, 13],
        [ 4,  2, 10],
        [ 8, 11,  5]]),
 array([[18, 16, 16],
        [ 8,  7, 16],
        [15, 19, 14]]))

In [91]:
m1 + [10, 10, 10]

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [92]:
m1 + [[1],[1],[1]]

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

# 행렬 내적 dot

In [94]:
np.dot(m1,m2), np.matmul(m1,m2), m1@m2

(array([[ 49,  51,  48],
        [136, 132, 132],
        [223, 213, 216]]),
 array([[ 49,  51,  48],
        [136, 132, 132],
        [223, 213, 216]]),
 array([[ 49,  51,  48],
        [136, 132, 132],
        [223, 213, 216]]))

In [95]:
m1@m2

array([[ 49,  51,  48],
       [136, 132, 132],
       [223, 213, 216]])