# 배열간 비교연산

In [2]:
import numpy as np
from numpy.random import choice

In [4]:
matrix_1 = choice(range(100),9).reshape(3,3)
matrix_2 = choice(range(100),9).reshape(3,3)

In [5]:
matrix_1, matrix_2

(array([[95, 63, 73],
        [95, 51,  7],
        [79, 54, 30]]),
 array([[48, 33,  3],
        [74, 64, 58],
        [27, 50, 59]]))

In [7]:
print(matrix_1 > matrix_2)
print(matrix_1 >= matrix_2)
print(matrix_1 == matrix_2)
print(matrix_1 != matrix_2)
print(matrix_1 <= matrix_2)
print(matrix_1 < matrix_2)

[[ True  True  True]
 [ True False False]
 [ True  True False]]
[[ True  True  True]
 [ True False False]
 [ True  True False]]
[[False False False]
 [False False False]
 [False False False]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[[False False False]
 [False  True  True]
 [False False  True]]
[[False False False]
 [False  True  True]
 [False False  True]]


In [8]:
# true false를 배열의 인덱스로 사용해서 true에 해당하는 데이터만 추출

In [9]:
matrix_1[matrix_1 > matrix_2]

array([95, 63, 73, 95, 79, 54])

In [10]:
print(matrix_1[matrix_1 > matrix_2])
print(matrix_1[matrix_1 >= matrix_2])
print(matrix_1[matrix_1 == matrix_2])
print(matrix_1[matrix_1 != matrix_2])
print(matrix_1[matrix_1 <= matrix_2])
print(matrix_1[matrix_1 < matrix_2])

[95 63 73 95 79 54]
[95 63 73 95 79 54]
[]
[95 63 73 95 51  7 79 54 30]
[51  7 30]
[51  7 30]


In [11]:
student_score = choice(range(60, 100), 9)
student_score

array([65, 83, 67, 94, 84, 80, 93, 97, 65])

In [21]:
student_names = np.array(['a','b','c','d','e','f','g','h','i'])
student_names

array(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i'], dtype='<U1')

In [13]:
# 정수가 70이상인 학생들을 출력

In [22]:
student_names[student_score >= 70]

array(['b', 'd', 'e', 'f', 'g', 'h'], dtype='<U1')

In [19]:
student_score[student_score >= 70]

array([83, 94, 84, 80, 93, 97])

# 판다스 pandas
    데이터분석에 자주 사용되는 프레임웍

## 시리즈

In [24]:
!pip install pandas

     --------------------------------------- 10.4/10.4 MB 11.5 MB/s eta 0:00:00


In [25]:
import pandas as pd

In [28]:
series_list_1 = pd.Series([1,2,3,4,5])
print(series_list_1)
print(series_list_1.index)
print(series_list_1.values)

0    1
1    2
2    3
3    4
4    5
dtype: int64
RangeIndex(start=0, stop=5, step=1)
[1 2 3 4 5]


In [29]:
series_list_1 = pd.Series([1,2,3,4,5], index = [10,20,30,40,50])
print(series_list_1)
print(series_list_1.index)
print(series_list_1.values)

10    1
20    2
30    3
40    4
50    5
dtype: int64
Int64Index([10, 20, 30, 40, 50], dtype='int64')
[1 2 3 4 5]


In [30]:
series_list_1 = pd.Series([1,2,3,4,5], index = ['a', 'b', 'c', 'd', 'e'])
print(series_list_1)
print(series_list_1.index)
print(series_list_1.values)

a    1
b    2
c    3
d    4
e    5
dtype: int64
Index(['a', 'b', 'c', 'd', 'e'], dtype='object')
[1 2 3 4 5]


In [31]:
series_list_1 = pd.Series([1,2,3,4,5],[1,2,3,4,5])
print(series_list_1)
print(series_list_1.index)
print(series_list_1.values)

1    1
2    2
3    3
4    4
5    5
dtype: int64
Int64Index([1, 2, 3, 4, 5], dtype='int64')
[1 2 3 4 5]


# 딕셔너리로 시리즈 생성하기

In [32]:
dic_data = {'치킨' :32000, '피자' : 25000, '햄버거' : 7000}
series_list_a = pd.Series(dic_data)
series_list_a

치킨     32000
피자     25000
햄버거     7000
dtype: int64

In [35]:
delivery_food = ['치킨', '피자', '햄버거', '짜장면']
dic_data = {'치킨' :32000, '피자' : 25000, '햄버거' : 7000}

series_list_a = pd.Series(dic_data, index = delivery_food)
series_list_a

치킨     32000.0
피자     25000.0
햄버거     7000.0
짜장면        NaN
dtype: float64

In [34]:
series_list_a = pd.Series([1,2,3,4], index = delivery_food)
series_list_a

치킨     1
피자     2
탕수육    3
짜장면    4
dtype: int64

### NaN: Not a Number --> 결측치

In [36]:
# 시리즈에서 값을 찾을 때
print(series_list_a['치킨'])
# 여러개를 찾을 때
print(series_list_a[['치킨', '피자']])

32000.0
치킨    32000.0
피자    25000.0
dtype: float64


In [37]:
# 조건에 해당하는 값을 찾을 때
series_list_a > 20000

치킨      True
피자      True
햄버거    False
짜장면    False
dtype: bool

In [38]:
# 인덱스가 있는지 확인할 때
print('치킨' in series_list_a)

True


In [39]:
print('치킨' in series_list_a.index)

True


In [40]:
series_list_a.values > 20000

array([ True,  True, False, False])

# 데이터 프레임: 시리즈들의 집합
    row, col / 행, 열 / index, columns

In [41]:
# 데이터 프레임 만들기
df = pd.DataFrame()

In [42]:
df['sex'] = ['M', 'M', 'W', 'W']

In [44]:
df['Age'] = [21, 25, 23, 20]

In [46]:
df['Name'] = ['Jihyun', 'Kyoungrok', 'Mina', 'Minseon']

In [47]:
df

sex  Age       Name
0   M   21     Jihyun
1   M   25  Kyoungrok
2   W   23       Mina
3   W   20    Minseon

### 데이터 프레임 만들기

In [50]:
# 컬럼을 지정 - 리스트
list_col = ['gender', 'age', 'name']
list_row = [
    ['M', 21, 'Jihyun'],
    ['M', 25, 'Kyoungrok'],
    ['W', 23, 'Mina'],
    ['W', 20, 'Minseon']
]

In [51]:
df = pd.DataFrame(list_row, columns=list_col)
df

gender  age       name
0      M   21     Jihyun
1      M   25  Kyoungrok
2      W   23       Mina
3      W   20    Minseon

In [53]:
# ndarray로 Dataframe
df = pd.DataFrame(np.array(list_row), columns=list_col)
df

gender age       name
0      M  21     Jihyun
1      M  25  Kyoungrok
2      W  23       Mina
3      W  20    Minseon

In [55]:
df.shape

(4, 3)

In [56]:
# 딕셔너리로 만들기
data_dic = {
 'category' : ['치킨', '피자', '햄버거'],
    'price' : [1000,2000,3000],
    'size' : [10,8,8]
}
pd.DataFrame(data_dic)

category  price  size
0       치킨   1000    10
1       피자   2000     8
2      햄버거   3000     8

In [57]:
# 리스트, 넘파이배열, 딕셔너리 <--> 데이터 프레임
# 1. 데이터프레임 -> 리스트
df.values.tolist()

[['M', '21', 'Jihyun'],
 ['M', '25', 'Kyoungrok'],
 ['W', '23', 'Mina'],
 ['W', '20', 'Minseon']]

In [59]:
# 2. 데이터프레임 -> 넘파이
df.values

array([['M', '21', 'Jihyun'],
       ['M', '25', 'Kyoungrok'],
       ['W', '23', 'Mina'],
       ['W', '20', 'Minseon']], dtype=object)

In [60]:
# 3. 데이터프레임 -> 딕셔너리
df.to_dict()

{'gender': {0: 'M', 1: 'M', 2: 'W', 3: 'W'},
 'age': {0: '21', 1: '25', 2: '23', 3: '20'},
 'name': {0: 'Jihyun', 1: 'Kyoungrok', 2: 'Mina', 3: 'Minseon'}}

In [61]:
df.to_dict('list')

{'gender': ['M', 'M', 'W', 'W'],
 'age': ['21', '25', '23', '20'],
 'name': ['Jihyun', 'Kyoungrok', 'Mina', 'Minseon']}

### 행과 열 삭제

In [63]:
data = [
    choice(range(60, 100), 4),
    choice(range(60, 100), 4),
    choice(range(60, 100), 4)
]
df = pd.DataFrame(data)
df

0   1   2   3
0  70  80  81  66
1  97  76  91  88
2  78  86  72  63

In [65]:
df.columns = ['국어', '영어', '수학', '과학']
df

국어  영어  수학  과학
0  70  80  81  66
1  97  76  91  88
2  78  86  72  63

In [66]:
df.index = ['철이', '미애', '영희']
df

국어  영어  수학  과학
철이  70  80  81  66
미애  97  76  91  88
영희  78  86  72  63

In [68]:
# 데이터 프레임 복사
df2 = df[ : ]
df2.drop(['철이', '미애'])

국어  영어  수학  과학
영희  78  86  72  63

In [70]:
dic_data = {'a':1, 'b':2, 'c':3}
se = pd.Series(dic_data)

In [71]:
se.index, se.values

(Index(['a', 'b', 'c'], dtype='object'), array([1, 2, 3], dtype=int64))

In [72]:
dic_data = {
    '이름' : '철이',
    '생년월일':'2000-01-01',
    '성별':'남',
    '학생여부':True
}
sr = pd.Series(dic_data)
sr

이름              철이
생년월일    2000-01-01
성별               남
학생여부          True
dtype: object

In [73]:
sr[0], sr['이름']

('철이', '철이')

In [74]:
sr[[1,2]]

생년월일    2000-01-01
성별               남
dtype: object

In [76]:
sr[['생년월일','성별']]

생년월일    2000-01-01
성별               남
dtype: object

In [77]:
sr[1:2]

생년월일    2000-01-01
dtype: object

In [78]:
sr['생년월일':'성별']

생년월일    2000-01-01
성별               남
dtype: object

In [80]:
dic_data = [
    choice(range(10), 3),
    choice(range(10), 3),
    choice(range(10), 3),
    choice(range(10), 3),
    choice(range(10), 3)
]
df = pd.DataFrame(dic_data)
df

0  1  2
0  1  4  0
1  5  1  1
2  9  2  7
3  3  7  0
4  9  2  3

In [81]:
dic_data = {
    'a':choice(range(10), 3),
    'b':choice(range(10), 3),
    'c':choice(range(10), 3),
    'd':choice(range(10), 3),
    'e':choice(range(10), 3)
}
df = pd.DataFrame(dic_data)
df

a  b  c  d  e
0  4  4  1  6  4
1  2  6  2  2  3
2  1  7  8  4  4

In [84]:
df['a'] # 결과가 시리즈

0    4
1    2
2    1
Name: a, dtype: int32

In [83]:
df[:2]

a  b  c  d  e
0  4  4  1  6  4
1  2  6  2  2  3

In [85]:
df[['a']] # 결과가 데이터 프레임

a
0  4
1  2
2  1

In [87]:
df.drop([0,1], axis=0)

a  b  c  d  e
2  1  7  8  4  4

In [88]:
df.drop(['a', 'b'], axis=1)

c  d  e
0  1  6  4
1  2  2  3
2  8  4  4

# 행 선택

In [90]:
data = [
    choice(range(100), 5),
    choice(range(100), 5),
    choice(range(100), 5),
    choice(range(100), 5),
    choice(range(100), 5)
]
df = pd.DataFrame(data)
df

0   1   2   3   4
0  56  97  95  97  32
1   4  70  80  57  35
2  39   1  72  72  49
3  47  25  24  32  48
4  67  96   8   0  65

In [91]:
df[0]

0    56
1     4
2    39
3    47
4    67
Name: 0, dtype: int32

In [93]:
# df[원소한개] 원소 한개: 스칼라, 벡터 --> 컬럼 데이터
# df[:] : 슬라이싱 --> 로우 데이터
df[[0,2]]

0   2
0  56  95
1   4  80
2  39  72
3  47  24
4  67   8

# loc / iloc
### 인덱스 기준
### loc 인덱스 이름 그대로
### iloc 인덱스이름과 상관없이 배열의 인덱스로 취급

In [94]:
df.loc[[1,0]]

0   1   2   3   4
1   4  70  80  57  35
0  56  97  95  97  32

In [95]:
df.loc[:3,:2]

0   1   2
0  56  97  95
1   4  70  80
2  39   1  72
3  47  25  24

In [96]:
df.iloc[:3,:2]

0   1
0  56  97
1   4  70
2  39   1

In [ ]:
df.columns['a', 'b', 'c', 'd', 'e']
df.index = ['i0', 'i1', 'i2', 'i3', 'i4']

In [97]:
df.iloc[0:4]

0   1   2   3   4
0  56  97  95  97  32
1   4  70  80  57  35
2  39   1  72  72  49
3  47  25  24  32  48

In [98]:
df['g'] = [0,0,0,0,0]
df

0   1   2   3   4  g
0  56  97  95  97  32  0
1   4  70  80  57  35  0
2  39   1  72  72  49  0
3  47  25  24  32  48  0
4  67  96   8   0  65  0

### iloc는 데이터를 추가할 수 없다

In [99]:
df.loc['i2', 'g'] = 10
df

0     1     2     3     4     g
0   56.0  97.0  95.0  97.0  32.0   0.0
1    4.0  70.0  80.0  57.0  35.0   0.0
2   39.0   1.0  72.0  72.0  49.0   0.0
3   47.0  25.0  24.0  32.0  48.0   0.0
4   67.0  96.0   8.0   0.0  65.0   0.0
i2   NaN   NaN   NaN   NaN   NaN  10.0

In [102]:
df.columns

Index([0, 1, 2, 3, 4, 'g'], dtype='object')

In [103]:
df2.reset_index(drop=True)

국어  영어  수학  과학
0  70  80  81  66
1  97  76  91  88
2  78  86  72  63